name: Apple Music test
on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Apple Music 連結（藝人 or 專輯，多條用空格）"
        required: true

jobs:
  gamdl_to_onedrive:
    runs-on: macos-latest
    env:
      DEST_DIR: musics/          # OneDrive 子目錄

    steps:

    - uses: actions/checkout@v4

    # 1. Python 3.12 + PyPI 穩定版 gamdl
    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }
    - name: Install gamdl
      run: python -m pip install -U pip gamdl

    # 2. macOS runner 補 FFmpeg
    - name: Install FFmpeg
      run: |
        brew update --quiet
        brew install ffmpeg

    # 3. 還原 cookies.txt
    - name: Restore cookies.txt
      env:
        AM_COOKIES_B64: ${{ secrets.AM_COOKIES_B64 }}
      run: |
        echo "$AM_COOKIES_B64" | base64 --decode > cookies.txt

    # 4. 下載 —— albums-only + no-prompt（用環境變量）
    - name: Download with gamdl
      run: |
        mkdir -p downloads
        read -ra URLS <<< "${{ github.event.inputs.urls }}"
        for u in "${URLS[@]}"; do
          GAMDL_ARTIST_TYPE=albums \
          GAMDL_DISABLE_PROMPT=1 \
          gamdl -o downloads -s "$u"
        done

    # 5. rclone 設定
    - uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
        disable_base64: true

    # 6. 上傳到 OneDrive
    - name: Upload to OneDrive
      run: |
        rclone copy downloads "od:${DEST_DIR}" \
          --transfers 32 --checkers 32 --fast-list \
          --progress --stats 30s
