name: Apple Music test

on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Apple Music 連結（空格分隔，可放藝人網址）"
        required:  true

jobs:
  gamdl_to_onedrive:
    runs-on: macos-latest
    env:
      DEST_DIR: musics/    # ← OneDrive 目標
    steps:
    - uses: actions/checkout@v4

    # 1. Python + gamdl
    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }
    - name: Install gamdl
      run: python -m pip install -U "git+https://github.com/glomatico/gamdl.git@main"

    # 3 確保 ffmpeg
    - name: Ensure ffmpeg
      run: |
        command -v ffmpeg || brew install ffmpeg

    # 4. cookies.txt
    - name: Restore cookies.txt
      env:
        AM_COOKIES_B64: ${{ secrets.AM_COOKIES_B64 }}
      run: |
        echo "$AM_COOKIES_B64" | base64 --decode > cookies.txt

    # 4. 下載 — albums-only + no-prompt + save-cover + mp4box
    - name: Download with gamdl
      run: |
        mkdir -p downloads
        read -ra URLS <<< "${{ github.event.inputs.urls }}"
        for u in "${URLS[@]}"; do
          gamdl -o downloads \
                --select albums \
                --no-prompt \
                --save-cover \
                "$u"
        done

    # 5. rclone & 上傳
    - uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
        disable_base64: true
    - name: Upload to OneDrive
      run: |
        rclone copy downloads "od:${DEST_DIR}" \
          --transfers 32 --checkers 32 --fast-list \
          --progress --stats 30s
