name: 高速 Rclone 文件搬运

on:
  workflow_dispatch:
    inputs:
      path:
        description: '源目录，相对于 new: Remote，比如：myFolder/ （注意带斜杠）'
        required: true
        default: ''

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 安装并加载 Rclone（纯文本 config）
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true

      - name: "高速拷贝 `${{ github.event.inputs.path }}` 到 od: 根目录"
        run: |
          echo "📁 源目录 = new:${{ github.event.inputs.path }}"
          echo "📁 目标目录 = od:"
          rclone copy \
            "new:${{ github.event.inputs.path }}" \
            "od:" \
            --transfers=32 \
            --checkers=32 \
            --fast-list \
            --multi-thread-streams=8 \
            --multi-thread-cutoff=16M \
            --buffer-size=1G \
            --drive-chunk-size=256M \
            --onedrive-chunk-size=64M \
            --progress \
            --stats=1s
        # 如果你的 rclone.conf 是加密的，取消下面这两行注释使用：
        # env:
        #   RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
