name: YTMusic → OneDrive (gytmdl + rclone)

on:
  workflow_dispatch:
    inputs:
      urls:
        description: "每行一个 YTMusic 链接（Song/Album/Playlist/Artist）"
        required: true
      dest_dir:
        description: "上传到 od: 下的目标目录，例如 Music/CleoSol/"
        required: true
      itag:
        description: "音质 itag（141=AAC256，774=Opus256，140=AAC128）"
        required: false
        default: "141"

jobs:
  run:
    runs-on: macos-latest  # Can be ubuntu-latest or other if needed

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install gytmdl & ffmpeg
      - name: Install gytmdl & ffmpeg
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade gytmdl
          brew install ffmpeg  # For Ubuntu, use apt-get install -y ffmpeg

      # Write cookies.txt from base64
      - name: Write cookies.txt from base64
        env:
          YTM_COOKIES_B64: ${{ secrets.YTM_COOKIES_B64 }}
        run: |
          python3 -c "
import os
import base64

# Get the base64 encoded cookies
b64_cookie = os.getenv('YTM_COOKIES_B64', '').strip()
if not b64_cookie:
    raise SystemExit('YTM_COOKIES_B64 is empty')

# Decode the base64 content and write it to cookies.txt
with open('cookies.txt', 'wb') as f:
    f.write(base64.b64decode(b64_cookie))
          "
          # Check if cookies.txt was created
          wc -l cookies.txt || true

      # Download with gytmdl
      - name: Download with gytmdl
        env:
          ITAG: ${{ github.event.inputs.itag }}
        run: |
          mkdir -p downloads
          gytmdl -r urls.txt -c cookies.txt -i "${ITAG:-141}" \
                 --save-cover -o downloads \
                 --template-folder "{album_artist}/{album}" \
                 --template-file "{track:02d} {title}"

      # Set up rclone and upload to OneDrive
      - name: Setup rclone (plain text config)
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true

      - name: Upload to OneDrive
        run: |
          SRC="downloads/"
          DST="od:${{ github.event.inputs.dest_dir }}"
          echo "SRC=$SRC"
          echo "DST=$DST"
          rclone copy "$SRC" "$DST" \
            --transfers=32 \
            --checkers=64 \
            --fast-list \
            --onedrive-chunk-size=60M \
            --buffer-size=1G \
            --multi-thread-streams=8 \
            --multi-thread-cutoff=16M \
            --progress \
            --stats=30s

      # Post-upload check
      - name: List remote target (post-check)
        run: rclone ls "od:${{ github.event.inputs.dest_dir }}" | head -n 50 || true
